In [1]:
# Import modul lokal
import sys
sys.path.append('../src')

In [5]:
pip install ccxt

Collecting ccxt
  Using cached ccxt-4.5.40-py2.py3-none-any.whl.metadata (138 kB)
Requirement already satisfied: setuptools>=60.9.0 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from ccxt) (80.9.0)
Requirement already satisfied: certifi>=2018.1.18 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from ccxt) (2026.2.25)
Requirement already satisfied: requests>=2.18.4 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from ccxt) (2.32.5)
Collecting cryptography>=2.6.1 (from ccxt)
  Downloading cryptography-46.0.5-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Requirement already satisfied: typing_extensions>=4.4.0 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from ccxt) (4.15.0)
Collecting aiohttp>=3.10.11 (from ccxt)
  Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Collecting aiodns>=1.1.1 (from ccxt)
  Using cached aiodns-4.0.0-py3-none-any.whl.metadata (7.7 kB)
Collecting yarl>=1.7.2 (from ccxt)
  Downloading yarl-1.22.0-cp311-cp311-win_amd64.whl.metadata (77 kB)
Collecting coincurve==21.0.0 (from ccxt)
  Downloading coincurve-21.0.0-cp311-cp311-win_amd64.whl.metadata (4.0 kB)
Collecting pycares<6,>=5.0.0 (from aiodns>=1.1.1->ccxt)
  Downloading pycares-5.0.1-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: cffi>=1.5.0 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from pycares<6,>=5.0.0->aiodns>=1.1.1->ccxt) (2.0.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp>=3.10.11->ccxt)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp>=3.10.11->ccxt)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from aiohttp>=3.10.11->ccxt) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp>=3.10.11->ccxt)
  Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp>=3.10.11->ccxt)
  Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp>=3.10.11->ccxt)
  Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: idna>=2.0 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from yarl>=1.7.2->ccxt) (3.7)
Requirement already satisfied: pycparser in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from cffi>=1.5.0->pycares<6,>=5.0.0->aiodns>=1.1.1->ccxt) (2.23)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from requests>=2.18.4->ccxt) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\miniconda3\envs\py311\lib\site-packages (from requests>=2.18.4->ccxt) (2.5.0)
Using cached ccxt-4.5.40-py2.py3-none-any.whl (6.5 MB)
Downloading coincurve-21.0.0-cp311-cp311-win_amd64.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.3 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 1.3/1.3 MB 4.0 MB/s  0:00:00
Using cached aiodns-4.0.0-py3-none-any.whl (11 kB)
Downloading pycares-5.0.1-cp311-cp311-win_amd64.whl (117 kB)
Downloading aiohttp-3.13.3-cp311-cp311-win_amd64.whl (457 kB)
Downloading multidict-6.7.1-cp311-cp311-win_amd64.whl (45 kB)
Downloading yarl-1.22.0-cp311-cp311-win_amd64.whl (86 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading cryptography-46.0.5-cp311-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ------ --------------------------------- 0.5/3.5 MB 3.4 MB/s eta 0:00:01
   ------------ --------------------------- 1.0/3.5 MB 3.0 MB/s eta 0:00:01
   ------------------ --------------------- 1.6/3.5 MB 2.9 MB/s eta 0:00:01
   ------------------------ --------------- 2.1/3.5 MB 2.7 MB/s eta 0:00:01
   ------------------------------ --------- 2.6/3.5 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------  3.4/3.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 2.6 MB/s  0:00:01
Downloading frozenlist-1.8.0-cp311-cp311-win_amd64.whl (44 kB)
Downloading propcache-0.4.1-cp311-cp311-win_amd64.whl (41 kB)
Installing collected packages: propcache, multidict, frozenlist, coincurve, aiohappyeyeballs, yarl, pycares, cryptography, aiosignal, aiohttp, aiodns, ccxt

   ------ ---------------------------------  2/12 [frozenlist]
   ---------------- -----------------------  5/12 [yarl]
   ----------------------- ----------------  7/12 [cryptography]
   ----------------------- ----------------  7/12 [cryptography]
   ----------------------- ----------------  7/12 [cryptography]
   -------------------------- -------------  8/12 [aiosignal]
   ------------------------------ ---------  9/12 [aiohttp]
   ------------------------------ ---------  9/12 [aiohttp]
   ------------------------------ ---------  9/12 [aiohttp]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ------------------------------------ --- 11/12 [ccxt]
   ---------------------------------------- 12/12 [ccxt]

Successfully installed aiodns-4.0.0 aiohappyeyeballs-2.6.1 aiohttp-3.13.3 aiosignal-1.4.0 ccxt-4.5.40 coincurve-21.0.0 cryptography-46.0.5 frozenlist-1.8.0 multidict-6.7.1 propcache-0.4.1 pycares-5.0.1 yarl-1.22.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from data_loader import fetch_full_history
from features import add_features_v2

# Ambil Data
df_coinbase = fetch_full_history(symbol='BTC/USD', start_date='2015-01-01T00:00:00Z')

In [9]:
df_coinbase.head()

              open    high     low   close       volume
timestamp
2015-07-20  277.98  280.00  277.37  280.00   782.883420
2015-07-21  279.96  281.27  276.85  277.32  4943.559434
2015-07-22  277.33  278.54  275.01  277.89  4687.909383
2015-07-23  277.96  279.75  276.28  277.39  5306.919575
2015-07-24  277.23  291.52  276.43  289.12  7362.469083

In [8]:
# Proses Fitur
btc_features_v2 = add_features_v2(df_coinbase)
btc_features_v2.head()

,open,high,low,close,volume,log_return,volatility,trend_slope,volume_zscore,price_dist_ma
timestamp,,,,,,,,,,
2015-09-12,240.90,241.12,235.26,236.50,5480.204714,-0.018434,0.026113,-0.016007,-0.580751,-0.067141
2015-09-13,236.50,236.91,229.72,230.82,5004.429976,-0.024310,0.026627,-0.017906,-0.719326,-0.085297
2015-09-14,230.83,233.99,228.01,231.01,7984.562513,0.000823,0.018803,-0.019933,0.206290,-0.079959
2015-09-15,231.02,232.43,230.26,230.60,7118.307926,-0.001776,0.014268,-0.021975,0.260590,-0.076915
2015-09-16,230.67,232.00,226.85,229.73,7655.652988,-0.003780,0.014026,-0.024469,0.755657,-0.075510

In [ ]:
import os
save_path = os.path.join('..', 'data', 'btc_usd_coinbase.csv')
save_path_features = os.path.join('..', 'data', 'btc_usd_coinbase_features_v2.csv')

df_coinbase.to_csv(save_path)
btc_features_v2.to_csv(save_path_features)